[[when-websocket-met-asciidoctor]]
= Real-time _collaborative_ editor for _AsciiDoc_
@mgreau 
v1.0, Apr 16, 2014
:hashtag:  #asciidoctor #WebSocket
:copyright: CC BY-SA 2.0
:website: http://asciidoctor.org
:dzslides-aspect: 16-9
:icons: font
:dzslides-style: devnation
:dzslides-fonts: family=Open+Sans:400,700,200,300
:dzslides-transition: fade
:dzslides-highlight: github
:language: highlight
:source-highlighter: highlightjs
:snippets: https://raw.github.com/mgreau/slides/master/websocket-asciidoctor/snippets

[[slide1]]
[.topic.intro]
== .

Maxime GREAU - France -

* twitter / github => @mgreau
* blog / website => http://mgreau.com

[NOTE.speaker]
====
. Text : Introduce myself

Hi, Thanks for coming, it's a honor for me to be here. So thanks to the DevNation team
My name is Maxime Gréau and I work for the French Ministry for Economy and Finances in France.
As you can hear, I'm a French guy. 
and I will do my best to be well understood despite my accent.

. Text : Overview

So I'm here to speak mainly about WebSocket Java EE 7 and Asciidoctor but also about HTML5, Angular and CDI
And I will show you how all this technology can fit together in order to do a Real-time Collaborative Editor for AsciiDoc
====


[[slide2]]
[.topic]
== Quick Pools

Its 4PM, how many people _sent an email today_ ?

And

How many people _wrote technical documentation_ in the past two days ?

Here we are !!

[NOTE.speaker]
====
. Ask to the attendees to hands up their hands

====


[[slide3]]
[.topic]
== AsciiDoc to the rescue

[.statement]
Writing documentation have to be as easy as writing email !


[NOTE.speaker]
====
. Text

Writing e-mail is easy. We do it all the time. Every day, we respond to dozens of e-mail
and social media messages. That involves communication through writing. That’s right, writing!

. References

http://asciidoctor.org/docs/what-is-asciidoc/
====

[[slide4]]
[.topic]
== What is AsciiDoc !

AsciiDoc is... 

* lightweight *markup*
* publishing *toolchain*

[NOTE.speaker]
====
. Text

Writing e-mail is easy. We do it all the time. Every day, we respond to dozens of e-mail
and social media messages. That involves communication through writing. That’s right, writing!

. References

http://asciidoctor.org/docs/what-is-asciidoc/
====

[[slide5]]
[.topic]
== Lightweight *markup* : example

---
[source, asciidoc]
----
include::{snippets}/snippets/asciidoctor_sample_asciidoc.adoc[]
----
---


[[slide7]]
[.topic]
== Publishing toolchain ?

"Use AsciiDoc for document markup. It's actually readable by humans, easier to parse way more flexible than XML."
-- Linus Torvald

[[slide8]]
[.topic]
== Asciidoctor ??

A modern, open source implementation of AsciiDoc [ruby]#in Ruby#


[[slide8]]
[.topic]
== Asciidoctor ??

What can I render from AsciiDoc file with Asciidoctor :

*




[[slide8]]
[.topic]
== Demo time

* Asciidoctor and Asciidoctor.js with ad-editor



[.ending]
== Thank you

[role="footer"]
http://github.com/mgreau/when-websocket-met-asciidoctor



